baseURL: https://trulede.github.io/hugo/
languageCode: en-us
title: Hugo Test Site.
theme: acedoc

module:
  imports:
    - path: github.com/trulede/raspberry.docker
      disable: false
      mounts:
        - source: doc
          target: content/repos
